### ISSUE TITLE
Training error: Too many open files

### ISSUE THREAD

**Issue by username1290** [FarFetchd/clickitongue#1]
Hi, saw your post on HN, tried to run it on OSX Big Sur, but got a message **at the end of the training**:
Too many open files.

Opened the app again and saw the training was not saved.

**Comment by FarFetchd** [comment]
Thanks for the report! I took a quick look just now at `lsof` on my Linux machine before, during, and after training; nothing that looked like cause for alarm. I will try it out on OSX later on, when I have access to the Macbook I test on. (Which I think is Big Sur as well).

My current theories are 1) on OSX, each std::thread (which the training makes dozens of at a time) opens its own fd behind the scenes for some reason; this would be pretty bizarre behavior but I don't know enough about OSX to rule it out.   2) basically just really bad luck; that there were enough other processes doing things with fds on your system at the time, and trying to write the config file happened to be what pushed it over the system limit.

Did you have any noteworthy amount of other stuff open at the time?

**Comment by FarFetchd** [comment]
Ok, figured it out! It's not std::thread, but rather std::random_device - looks like on OSX it opens /dev/urandom, and holds it open. And Clickitongue's training makes (leaks actually, lol) ~800 of them, enough to have a decent chance of hitting the systemwide limit on a busy system. I will fix that now.

**Comment by FarFetchd** [comment]
Ok, tested on OSX with the new commit I just pushed to master a few minutes ago, and `lsof` for clickitongue stays nice and low. That should fix it. Thanks again for bringing this to my attention!
